version: '3.5'
services:
 web_dev:
  build: .
  ports:
   - "10444:10444"
  volumes:
   - .:/app
  environment:
   - ENV=production
   - PORT=10444
   - DB=mongodb://mongodb:27017/todoDev
#  mongodb:
#   image: mongo:latest
#   container_name: "mongodb"
#   environment:
#    - MONGO_DATA_DIR=/usr/data/db
#    - MONGO_LOG_DIR=/dev/null
#   volumes:
#    - ./data/db:/usr/data/db
#   ports:
#    - 27017:27017
#   command: mongod --smallfiles --logpath=/dev/null # --quiet
networks:
 default:
  name: web_dev
